name: CI

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == github.event.repository.default_branch
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        cache: npm
        node-version-file: .nvmrc
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci
